Use portable-atomic to support PowerPC
Use the portable-atomic crate to fix build failure on PowerPC target
that does not support 64-bit atomics natively:

```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> src/archive.rs:7:18
  |
7 |         atomic::{AtomicU64, Ordering},
  |                  ^^^^^^^^^
  |                  |
  |                  no `AtomicU64` in `sync::atomic`
  |                  help: a similar name exists in the module: `AtomicU32`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `tokio-tar` (lib) due to 1 previous error
```